### ISSUE TITLE
examples: grepping in files for text fragments

### ISSUE THREAD

**Issue by matu3ba** [jake-stewart/jfind.nvim#1]
First of all, thanks for the plugin and fuzzy finder.
It would be nice to have examples for grepping for text fragments with ripgrep, which is my main (leakage) problem with telescope.
I have something handcrafted for one-shot programs with plenary, but explorative fuzzy finding is much much more usable.

As of now, I do see only `findFile` and no `grepFile`.
I do see that you pipe through multiple processes in `jfind-file.sh`, which could be problematic for huge input texts.

**Comment by jake-stewart** [comment]
how would the grep file work? Would it work like running `grep -r "regex" | jfind`, and then let you perform fuzzy search on the returned lines, or would it let you type out the regex interactively?

**Comment by matu3ba** [comment]
Interactively would be ideal, but I'm not sure how much complexity that means. I need to think abit more how 1. rg/grep args + 2. fuzzy matching could work, but I suspect the most general solution is to make both adjustible.

**Comment by jake-stewart** [comment]
if we're to add interactive regex, then that would mean adding regex as a jfind matching strategy. then we just cat every file into jfind and use the regex strategy when matching.

otherwise, we use the regular jfind matching but only pipe in the results of the ripgrep into jfind.

the second option is very easy to do and already supported by jfind.

**Comment by jake-stewart** [comment]
@matu3ba i implemented a regex matcher in jfind, could i get you to install the latest jfind, and test it out to see if it's what you're after?

run this bash script from your shell in a codebase:
```
#!/bin/bash
set -e

CACHE="$XDG_CACHE_HOME"
test -z "$CACHE" && CACHE="$HOME/.cache"
EXCLUDES="$CACHE/jfind_excludes"

command_exists() {
    type "$1" &> /dev/null
}

list_files() {
    command_exists fd && fd_command="fd"
    command_exists fdfind && fd_command="fdfind"

    if [ -n "$fd_command" ]; then
        exclude=$(cat "$EXCLUDES" 2>/dev/null \
            | sed "s/'/'\"'\"'/g" | awk "{printf \" -E '%s'\", "'$0}')
        eval "$fd_command --type f $exclude"
    else
        exclude=$(cat "$EXCLUDES" 2>/dev/null \
            | sed "s/'/'\"'\"'/g" \
            | awk "{printf \" ! -path '*/%s/*' ! -iname '%s'\", "'$0, $0}')
        eval "find '.' -type f $exclude"
    fi
}

cat_files() {
    for file in $(list_files); do
        cat $file | awk '{print $0; print "'"$file"':" NR}'
    done
}

cat_files | jfind --matcher=regex --hints --select-hint
```

**Comment by matu3ba** [comment]
Will do after work today or at latest tomorrow.

**Comment by matu3ba** [comment]
It kinda does what I want, although the cursor is not very stable (so not usable)
https://asciinema.org/a/R2gYzt69PxL2Zu9WGTEZLPHt6

If I use it within zellij as multiplexer, the problem appears to becomes worse, but I'm not entirely sure about that.

On a huge repo like Linux it gets worse:
https://asciinema.org/a/TF5Kqq7GdoSguLzth3vMwRWya

Do I need to configure anything additionally?

**Comment by jake-stewart** [comment]
thanks i'll take a look and get back to you

**Comment by jake-stewart** [comment]
@matu3ba the cursor jumping issue should be fixed.

i played around with it myself and did some testing. i realised the way jfind is optimised for fuzzy finding makes it very poor for grepping.

with grep, you do not need to load in the entire buffer of every file. you just read one line at a time and output that line if it matches. you don't need to load the buffer into memory because you do not sort anything.

the correct approach now would be to add some sort of --command flag, where you would provide a command which runs after each keypress. for example `--command="rg {}"`.

my main concern now is whether this is out of scope.

**Comment by matu3ba** [comment]
> my main concern now is whether this is out of scope.

Mhm, how much implementation complexity would that be? 
I'd probably doing something like tracking if the previous word has common prefix or matches the same regex and otherwise dump results and reanalyze by spawning a new process.
(I did some process stuff like that in Zig including looking at the windows process shennanigans.)

However, afaik, there is no good child process api in c++ libstd and you probably dont wan to use boost as heavy dependency.

**Comment by jake-stewart** [comment]
i'll take a look at it today. it shouldn't be too complex. it every time the user types something, it will spawn a process with `fork` and kill any ongoing one and clearing the items list. it will read the new processes stdout using `dup2`. it will not sort anything itself.

i'll let you know how it goes

**Comment by jake-stewart** [comment]
it's working great. very fast now. i've got a little bit of code cleaning left to do before i put it in master.

could i get you to build and test out the [command](https://github.com/jake-stewart/jfind/tree/command) branch of jfind?

Launch jfind using this command:
```bash
jfind --command="rg -n {}" | awk -F: '{print $1 ":" $2}'
```

EDIT: at the moment it looks ugly because I have not added hints support to the command executor. soon we will be able to format it so that only the line content is on the left column and the filename + line number is on the right.

**Comment by matu3ba** [comment]
eabcee96272902070baad25822235fdface8db36 does not build:
```
/home/user/dev/git/cpp/jfind/src/item_list.cpp: In Elementfunktion »void ItemList::drawHint(int) const«:
/home/user/dev/git/cpp/jfind/src/item_list.cpp:65:43: Fehler: »strlen« wurde in diesem Gültigkeitsbereich nicht definiert
   65 |     std::string hint = std::string(text + strlen(text) + 1);
      |                                           ^~~~~~
/home/user/dev/git/cpp/jfind/src/item_list.cpp:2:1: Anmerkung: »strlen« ist im Header »<cstring>« definiert; haben Sie vergessen, »#include <cstring>« zu schreiben?
    1 | #include "../include/item_list.hpp"
  +++ |+#include <cstring>
    2 |
make[2]: *** [CMakeFiles/jfind.dir/build.make:272: CMakeFiles/jfind.dir/src/item_list.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet …
/home/user/dev/git/cpp/jfind/src/item_generator.cpp: In Elementfunktion »void ItemGenerator::endChildProcess()«:
/home/user/dev/git/cpp/jfind/src/item_generator.cpp:123:5: Fehler: »waitpid« wurde in diesem Gültigkeitsbereich nicht definiert
  123 |     waitpid(m_child_pid, &status, 0);
      |     ^~~~~~~
make[2]: *** [CMakeFiles/jfind.dir/build.make:258: CMakeFiles/jfind.dir/src/item_generator.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/jfind.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
```

**Comment by jake-stewart** [comment]
sorry, should work now.
EDIT: make sure you have ripgrep installed. jfind will not tell you if the --command flag fails

**Comment by jake-stewart** [comment]
i assume you're using linux. i've tested it out on a vm and it has a few things i need to fix. i'll let you know when it's good to go @matu3ba

**Comment by jake-stewart** [comment]
@matu3ba i went a bit overboard

i made it so when you type a query with --command, it launches a process and suspends it after 128 lines of output. if you scroll up close to 128, then it resumes the process to generate another 128 lines. so on so forth. this allows us to ripgrep without using much cpu and memory usage, only loading more results as needed.

the command branch is probably fully completed now. I've tested and it works great for linux.

let me know how it goes, thanks. if everything works great then i'll work on creating a liveGrep function for jfind.nvim.

EDIT: you could also try out this command which is probably how jfind.nvim would end up showing it:

```
jfind --hints --select-hint --command="rg -n {} | awk -F: '{print substr(\$0, index(\$0,\$3)); print \$1 \":\" \$2}'"
```

**Comment by matu3ba** [comment]
With
```diff
diff --git a/src/process.cpp b/src/process.cpp
index a1cb04f..52774fc 100644
--- a/src/process.cpp
+++ b/src/process.cpp
@@ -1,6 +1,7 @@
 #include "../include/process.hpp"
 
 #include <csignal>
+#include <cstdlib>
 
 #define READ 0
 #define WRITE 1
```
applied against e79dd6a0823c2f63ed8d1f9f3ebadc81c344927e, I get it building and it works like a charm. Would you be interested in a CI contribution?

**Comment by jake-stewart** [comment]
yes always happy for contributions

**Comment by matu3ba** [comment]
done: https://github.com/jake-stewart/jfind/pull/13

**Comment by jake-stewart** [comment]
🥳 pushed `liveGrep()` to 1.0 branch. Make sure jfind is built and read readme for usage
