### ISSUE TITLE
Escape to close jfind dialog

### ISSUE THREAD

**Issue by technicalpickles** [jake-stewart/jfind.nvim#10]
Not sure how feasible this is. I have gotten into the habit of hitting escape to close my fuzzy find dialog. When I do that with jfind.nvim, I think I end up in normal mode, which then I have to `:q` to exit.

Also worth noting you can't edit in normal mode inside a jfind dialog, as you get `cannot make changes, modifiable is "off"`.

Can the key callbacks be used for this? I am looking at the source, and wasn't able to figure out what the arguments are that are passed to the callbacks.

**Comment by jake-stewart** [comment]
that's strange. it's supposed to exit by pressing escape. i might have some config i was unaware of.

**Comment by jake-stewart** [comment]
could you record a video or send screenshots which capture this problem?

EDIT: we can see from the lua that the window is closed once jfind finishes.
I suspect that you have a mapping for the neovim terminal for escape which goes into normal mode?
If this is the case, then I may want to override that mapping just for the jfind window

```lua
    vim.fn.termopen(cmd, {on_exit = function(_, status, _)
        vim.api.nvim_win_close(win, 0)
        if status == 0 then
            onComplete()
        end
    end})
```

**Comment by jake-stewart** [comment]
i put out an update to 1.0 which may or may not fix this problem for you

**Comment by technicalpickles** [comment]
That fixed it, thanks!

I wasn't aware of a mapping in terminal, so will have to go figure out what that is about.
