### ISSUE TITLE
Vim Keybindings

### ISSUE THREAD

**Issue by geefuoco** [jake-stewart/jfind.nvim#13]
Is it possible to enable vim key bindings in the search window ? 

![image](https://github.com/jake-stewart/jfind.nvim/assets/87877876/9f8220c1-1998-4b02-9f82-be7cc3158343)

Currently when the window is open, I have to use the arrow keys to navigate

**Comment by jake-stewart** [comment]
it should support ctrl + j and k to navigate up and down. it is possible that these keys are remapped for you. if this is the case, i should automatically unmap them while in the popup.

if this isn't the case, then what terminal are you using?

**Comment by jake-stewart** [comment]
the 2.0 branch automatically overrides common bindings so this shouldn't be a problem for basic jfind usage.
you will need to recompile jfind and use jfind.nvim 2.0 branch.
