### ISSUE TITLE
Feature request for live grep arguments

### ISSUE THREAD

**Issue by faridsaid20** [jake-stewart/jfind.nvim#16]
For example it would be good to only show results from specific directories, path,
or file types?

Similar to this plugin for telescope grep args.
https://github.com/nvim-telescope/telescope-live-grep-args.nvim

**Comment by jake-stewart** [comment]
currently you can provide a custom list of excludes to liveGrep.
i could allow a custom list of includes, too. this would only show results from specific directories/paths/file types.
are there any other flags you would need?

**Comment by jake-stewart** [comment]
i could allow a start query too. that way you could write logic to livegrep the word under the cursor

**Comment by jake-stewart** [comment]
i pushed to 2.0 branch `includes` and `query` options.

you can play around with the following example:
```lua
                local jfind = require("jfind")
                local Key = require("jfind.key")
                jfind.liveGrep({
                    exclude = {"some_file.cpp", "another_file.cpp"},
                    include = {"*.cpp"},
                    query = "test",
                    hidden = true,
                    preview = true,
                    previewPosition = "bottom",
                    queryPosition = "top",
                    caseSensitivity = "smart",
                    callback = {
                        [Key.DEFAULT] = jfind.editGotoLine,
                        [Key.CTRL_B] = jfind.splitGotoLine,
                        [Key.CTRL_N] = jfind.vsplitGotoLine,
                    }
                })
```

let me know if any options you want are missing

**Comment by faridsaid20** [comment]
Yes, this is good if you know already which directories to filter, but most of the time you will need to filter different directories depending on what you are searching for.

Here is example :)
I open live grep, start writing for:

key

which may result in these files

init.lua
after/init.lua
plugin/init.lua

Then I just modify my search without closing the live grep to
"key" after

now it should immediately show matches only from "after" directory. 
Here is how it works in telescope-live-grep-args.nvim

https://github.com/jake-stewart/jfind.nvim/assets/119894088/f3af2fc7-8bbb-4609-bbb2-dc7effb0aaeb

**Comment by jake-stewart** [comment]
@faridsaid20 you could possibly create your own jfind function for this:

```lua
local jfind = require("jfind")
local Key = require("jfind.key")

local preview;
if vim.fn.executable("bat") == 1 then
    preview = "bat --color always --theme ansi --style plain"
else
    preview = "cat"
end
preview = preview .. " $(echo {} | awk -F: '{print $1}')"

jfind.jfind({
    preview = preview,
    previewPosition = "top",
    query = "",
    caseSensitivity = "smart",
    history = "~/.cache/jfind_live_grep_args_history",
    command = "bash -c 'rg '{}",
    callback = {
        [Key.DEFAULT] = jfind.editGotoLine,
        [Key.CTRL_B] = jfind.splitGotoLine,
        [Key.CTRL_N] = jfind.vsplitGotoLine,
    }
})
```

it works as expected but you need to manually quote the first argument if it contains spaces. there is currently no way to have a keybinding manipulate the query in jfind.

**Comment by jake-stewart** [comment]
i think in the end i'm going to have to implement ways to bind custom functionality in jfind

**Comment by faridsaid20** [comment]
Nice, works good ;) Thank you
Could you take a look at my question in here?
https://github.com/jake-stewart/jfind.nvim/issues/15#event-9682014990
