### ISSUE TITLE
Feature request: --no-ignore flag option/custom flags option

### ISSUE THREAD

**Issue by AndroAmater** [jake-stewart/jfind.nvim#17]
Hi, I've been using jfind.nvim with `jfind.findFile` and a `--no-ignore` flag option for `rg` would really come in handy to search in all files in a project. I see in the source that other flags are supported so would it be too much work to add this?  (p.s. I tried `include: {"*"}`, but it doesn't work like it does with `jfind.findGrep`)

On a not-so separate note:

I would also love to have a general flags option to set custom flags. I know that I will always use `rg` so I know which flags I want to pass to it and am not worried about compatibility with other tools. Not sure what your philosophy for adding not cross-compatible options is or if this would be too much work though. 

Being able to pass parameters like `--sort="path"` would be nice, if you want the results to be sorted in a deterministic order (even at the cost of speed). There are other exmples like `--search-zip` or `--no-ignore-global` that could come in handy. I think there are likely too many flags for implementing lua options for each, especially considering cross compatibility with other tools. I know you can write a custom `jfind` statement but having this as part of `jfind.findFile` would make it a lot easier IMO.

If something like this sounds good to you I can create a MR with an example implementation in the following days. I can also add smmilar options for `jfind.findGrep` if you'd like.

Thanks for the good work so far :grin:  :rocket: !

**Comment by jake-stewart** [comment]
@AndroAmater i’ll add/fix the include option to findFile later today. i’m more than happy for a general flags option. could have it called “fdFlags” and “findFlags”. same logic for live grep.

edit: in case im not clear, im happy for PRs!

**Comment by AndroAmater** [comment]
Hi @jake-stewart , I didn’t get notified so I’m responding kinda late 😅

Great to hear that something like a general flag would work for you, I’ll code something up this weekend and submit it for RFC.

**Comment by jake-stewart** [comment]
i can see you're a busy man @AndroAmater.
i have added the `rgFlags` and `grepFlags` options to `liveGrep`.

here is an example usage:
```lua
jfind.liveGrep({
    rgFlags = {
        "-m", "1"
    },
})
```
