### ISSUE TITLE
use stdpath instead of hardcoding HOME and cache

### ISSUE THREAD

**Issue by matu3ba** [jake-stewart/jfind.nvim#2]
Note, that `local HOME = vim.fn.getenv("HOME")` also fails on Windows and likewise the used path delimiters.
There is a workaround https://github.com/matu3ba/dotfiles/blob/master/.config/nvim/lua/my_utils.lua#L25 and below.

Not sure, what the best approach for windows support could be, but it would be nice to mention that WSL works.

**Comment by jake-stewart** [comment]
wsl should work, right? i haven't tested it though.
i do not care about supporting regular windows. i don't even know if jfind works on regular windows.

**Comment by jake-stewart** [comment]
i have made it try to use `XDG_CACHE_HOME`, falling back to `~/.cache` if it is not set.
