### ISSUE TITLE
[Feat] Support quickfix redirection for matches

### ISSUE THREAD

**Issue by vihu** [jake-stewart/jfind.nvim#22]
Hello,

I was wondering if you'd be willing to support a keybind to pass the results to the vim quickfix window. For example, I press `ctrl + q` and it should send the match results (files/livegrep) to the quickfix window. [Here's](https://github.com/ibhagwan/fzf-lua/issues/324) a similar issue for reference on fzf-lua.nvim.

It's quite handy to be able to do it this way because I can then use something like [quickfix-reflector](https://github.com/stefandtw/quickfix-reflector.vim) to search and replace the matches for example.

Any alternative suggestion would work as well :)

Thanks!

**Comment by jake-stewart** [comment]
hi

you can use `selectAll = true`

```lua

local jfind = require("jfind")
local Key = require("jfind.key")

jfind.liveGrep({
    selectAll = true,
    callback = {
        [Key.DEFAULT] = function(results)
            local qflist = {};
            for i, v in pairs(results) do
                qflist[i] = {filename = v[1], lnum = v[2]}
            end
            vim.fn.setqflist(qflist)
        end
    }
})

```

the downside is that you need a mapping for select all and not select all. i plan on adding lua in the late future to allow for more scriptability like this.
