### ISSUE TITLE
module jfind.key not found

### ISSUE THREAD

**Issue by ComputerDuck** [jake-stewart/jfind.nvim#6]
When I try to remap my keys in jfind it tells me that there is no module called key in jfind. I installed the normal jfind with the given command, then I added the plugin to my lackage manager (lazy) and copied the basic config. 

But from what I can see from the repo there doesn't seem to be a module named key anyways.

**Comment by jake-stewart** [comment]
the "jfind.key" is only on the 1.0 branch. the readme shows how to install a branch using most common package managers.
if this isn't the case, please post your config. thanks

**Comment by jake-stewart** [comment]
you can use my config as reference if you want, since i use lazy too.

```lua
require("lazy").setup({
    {
        "jake-stewart/jfind.nvim", branch = "1.0",
        keys = {
            {"<c-f>", function()
                local Key = require("jfind.key")
                require("jfind").findFile({
                    formatPaths = true,
                    callback = {
                        [Key.DEFAULT] = vim.cmd.edit,
                        [Key.CTRL_S] = vim.cmd.split,
                        [Key.CTRL_V] = vim.cmd.vsplit,
                    }
                })
            end},
        },
        config = function()
            require("jfind").setup({
                exclude = {
                    ".git",
                    ".idea",
                    ".vscode",
                    ".sass-cache",
                    ".class",
                    "__pycache__",
                    "node_modules",
                    "target",
                    "build",
                    "tmp",
                    "assets",
                    "dist",
                    "public",
                    "*.iml",
                    "*.meta"
                },
                border = "rounded",
                formatPaths = true,
                key = "<c-f>",
                tmux = true,
            });
        end
    },
})
```

**Comment by ComputerDuck** [comment]
> the "jfind.key" is only on the 1.0 branch. the readme shows how to install a branch using most common package managers.
> 
> if this isn't the case, please post your config. thanks

You're right, I forgot to sync lazy

**Comment by technicalpickles** [comment]
Came to report this too.

I'm a little confused... does main not include `jfind.key`? I had installed before there were instructions to use the 1.0 branch, so was just updating what I had configured (ie main). It has docs for the jfind.key, but not the actual file 🤔
