### ISSUE TITLE
File Previews?

### ISSUE THREAD

**Issue by ComputerDuck** [jake-stewart/jfind.nvim#7]
Not really an Issue, more of a question. Will there be file previews in the future or is it a design choice not to include file previews?

**Comment by jake-stewart** [comment]
less of a design choice and more of a "i dont use them so i wont add them".

so i'm not against the idea. if someone makes a good PR, then i'll add it in. i just wont do it myself.

**Comment by jake-stewart** [comment]
i added file previews. you can use them by recompiling jfind and using jfind.nvim 2.0 branch.
