### ISSUE TITLE
Finding files that start with dot (.)

### ISSUE THREAD

**Issue by technicalpickles** [jake-stewart/jfind.nvim#8]
A lot of the projects I work in end up having dotfiles, ie `.rubocop.yml`. I'm not able to fuzzy find them with jfind.nvim

When I was using telescope with `fd`, I was able to do this with `--hidden`. I _think_ this would be a matter of adding it to `scripts/jfind-file.sh`? It seems I could also make my own mapping, and call `require('jfind').jfind` with my own script 🤔

**Comment by jake-stewart** [comment]
i completely overlooked this. i'll add an option to findfile called hidden or similar

**Comment by jake-stewart** [comment]
Updated the 1.0 branch to have the `hidden` option. it defaults as true so should work right out of the box after you update.
